In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


## Series

In [2]:
# create a series
series1 = Series([1,3,5,7])
print(series1)

# values of the seris
print("\n", series1.values)

# index of series
print("\n", series1.index)

0    1
1    3
2    5
3    7
dtype: int64

 [1 3 5 7]

 RangeIndex(start=0, stop=4, step=1)


In [3]:
# lets create a series data for the worldwar2 casualties
ww2_cas = Series([8700000,4300000,3000000,2100000,400000],index=['USSR','Germany','China','Japan','USA'])
print(ww2_cas)

# we can slice and dice  series obj
ww2_cas['USA']

# we can filter records
# example: find the countries that has casualties greater then 4mm
ww2_cas[ww2_cas > 4000000]

USSR       8700000
Germany    4300000
China      3000000
Japan      2100000
USA         400000
dtype: int64


USSR       8700000
Germany    4300000
dtype: int64

In [4]:
# we can treat Series as ordered dictionary

# check if USSR is in Series
'USSR' in ww2_cas

True

In [5]:
# we can convert Series into Python dictionary
ww2_dict = ww2_cas.to_dict()

#Show
print(ww2_dict)

# we can convert back into a Series
WW2_Series = Series(ww2_dict)
print(WW2_Series)

{'USSR': 8700000, 'Germany': 4300000, 'China': 3000000, 'Japan': 2100000, 'USA': 400000}
China      3000000
Germany    4300000
Japan      2100000
USA         400000
USSR       8700000
dtype: int64


## DataFrames

In [6]:
# DataFrames

# Let's get some data to play with. How about the NFL?
import webbrowser
website = 'https://en.wikipedia.org/wiki/NFL_winloss_records'
webbrowser.open(website)


True

In [10]:
# copy the first 5 rows from the wiki page and use it to create the dataframe
# using the read_clipboard
nfl_frame = pd.read_clipboard()
nfl_frame

Rank               Team  Won  Lost  Tied   Pct.  First NFL Season  \
0     1     Dallas Cowboys  502   374     6  0.573              1960   
1     2  Green Bay Packers  737   562    37  0.565              1921   
2     3      Chicago Bears  749   579    42  0.562              1920   
3     4     Miami Dolphins  445   351     4  0.559              1966   

  Total Games   Division  
0         882   NFC East  
1       1,336  NFC North  
2       1,370  NFC North  
3         800   AFC East

In [11]:
print(nfl_frame.columns)

# we can retrieve by column names
print(nfl_frame['Rank'])

# we can retrieve multiple columns
print(DataFrame(nfl_frame, columns = ['Team', 'First NFL Season', 'Total Games']))

Index(['Rank', 'Team', 'Won', 'Lost', 'Tied', 'Pct.', 'First NFL Season',
       'Total Games', 'Division'],
      dtype='object')
0    1
1    2
2    3
3    4
Name: Rank, dtype: int64
                Team  First NFL Season Total Games
0     Dallas Cowboys              1960         882
1  Green Bay Packers              1921       1,336
2      Chicago Bears              1920       1,370
3     Miami Dolphins              1966         800


In [12]:
nfl_frame[['Rank','Team','First NFL Season', 'Total Games']]

Rank               Team  First NFL Season Total Games
0     1     Dallas Cowboys              1960         882
1     2  Green Bay Packers              1921       1,336
2     3      Chicago Bears              1920       1,370
3     4     Miami Dolphins              1966         800

In [13]:
# pandas can deal with columns that does not have exist
# for instance if we add 'Stadium' column to our dataframe, pandas handles it by filling in Nan values

DataFrame(nfl_frame, columns = ['Rank','Team','First NFL Season', 'Total Games', 'Stadium'])

Rank               Team  First NFL Season Total Games  Stadium
0     1     Dallas Cowboys              1960         882      NaN
1     2  Green Bay Packers              1921       1,336      NaN
2     3      Chicago Bears              1920       1,370      NaN
3     4     Miami Dolphins              1966         800      NaN

In [14]:
# We can also assign values to entire columns
nfl_frame['Stadium'] = "Levi's Stadium"
nfl_frame

Rank               Team  Won  Lost  Tied   Pct.  First NFL Season  \
0     1     Dallas Cowboys  502   374     6  0.573              1960   
1     2  Green Bay Packers  737   562    37  0.565              1921   
2     3      Chicago Bears  749   579    42  0.562              1920   
3     4     Miami Dolphins  445   351     4  0.559              1966   

  Total Games   Division         Stadium  
0         882   NFC East  Levi's Stadium  
1       1,336  NFC North  Levi's Stadium  
2       1,370  NFC North  Levi's Stadium  
3         800   AFC East  Levi's Stadium

In [15]:
nfl_frame['Stadium'] = np.arange(4)
nfl_frame

Rank               Team  Won  Lost  Tied   Pct.  First NFL Season  \
0     1     Dallas Cowboys  502   374     6  0.573              1960   
1     2  Green Bay Packers  737   562    37  0.565              1921   
2     3      Chicago Bears  749   579    42  0.562              1920   
3     4     Miami Dolphins  445   351     4  0.559              1966   

  Total Games   Division  Stadium  
0         882   NFC East        0  
1       1,336  NFC North        1  
2       1,370  NFC North        2  
3         800   AFC East        3

In [16]:
# we can assign a series object to the dataframe
stadiums = Series(["Levi's Stadium", "AT&T Stadium"])
print(stadiums)

nfl_frame['Stadium'] = stadiums
nfl_frame

0    Levi's Stadium
1      AT&T Stadium
dtype: object


Rank               Team  Won  Lost  Tied   Pct.  First NFL Season  \
0     1     Dallas Cowboys  502   374     6  0.573              1960   
1     2  Green Bay Packers  737   562    37  0.565              1921   
2     3      Chicago Bears  749   579    42  0.562              1920   
3     4     Miami Dolphins  445   351     4  0.559              1966   

  Total Games   Division         Stadium  
0         882   NFC East  Levi's Stadium  
1       1,336  NFC North    AT&T Stadium  
2       1,370  NFC North             NaN  
3         800   AFC East             NaN

In [17]:
# we can assign a series object to the dataframe
# we pass the index value in this case, notice the diff
stadiums = Series(["Levi's Stadium", "AT&T Stadium"], index = [4, 2])
print(stadiums)

nfl_frame['Stadium'] = stadiums
nfl_frame

4    Levi's Stadium
2      AT&T Stadium
dtype: object


Rank               Team  Won  Lost  Tied   Pct.  First NFL Season  \
0     1     Dallas Cowboys  502   374     6  0.573              1960   
1     2  Green Bay Packers  737   562    37  0.565              1921   
2     3      Chicago Bears  749   579    42  0.562              1920   
3     4     Miami Dolphins  445   351     4  0.559              1966   

  Total Games   Division       Stadium  
0         882   NFC East           NaN  
1       1,336  NFC North           NaN  
2       1,370  NFC North  AT&T Stadium  
3         800   AFC East           NaN

In [18]:
# we can also delete the entire column
del nfl_frame['Stadium']

In [19]:
nfl_frame

Rank               Team  Won  Lost  Tied   Pct.  First NFL Season  \
0     1     Dallas Cowboys  502   374     6  0.573              1960   
1     2  Green Bay Packers  737   562    37  0.565              1921   
2     3      Chicago Bears  749   579    42  0.562              1920   
3     4     Miami Dolphins  445   351     4  0.559              1966   

  Total Games   Division  
0         882   NFC East  
1       1,336  NFC North  
2       1,370  NFC North  
3         800   AFC East

In [20]:
# DataFrames can be constructed from a dictionary of equal length lists
data = {'City':['SF','LA', 'NYC'],
        'Population':[837000,3880000,8400000]}

city_frame = DataFrame(data)

#Show
city_frame

City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000

## Index Objects

In [21]:
ser1 =  Series([1,2,3,4], index=['A','B','C','D'])
print(ser1)
print(ser1.index)
my_index = ser1.index
print(my_index)
print(my_index[2])

# indexes are immutable
my_index[0] = 'AA'

A    1
B    2
C    3
D    4
dtype: int64
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['A', 'B', 'C', 'D'], dtype='object')
C


TypeError: Index does not support mutable operations

In [22]:
# Reindexing

from numpy.random import randn

#Lets create a new series
ser1 = Series([1,2,3,4],index=['A','B','C','D'])
ser1






A    1
B    2
C    3
D    4
dtype: int64

In [23]:
ser1

A    1
B    2
C    3
D    4
dtype: int64

In [24]:
#Call reindex to rearrange the data to a new index
ser2 = ser1.reindex(['A','B','C','D','E','F'])
ser2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [25]:
# We can also fill in values for new indexes
ser2.reindex(['A','B','C','D','E','F','G'],fill_value=0)


A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
G    0.0
dtype: float64

In [26]:
#Using a particular method for filling values
ser3 = Series(['USA','Mexico','Canada'],index=[0,5,10])
ser3


0        USA
5     Mexico
10    Canada
dtype: object

In [27]:
#Can use a forward fill for interploating values vetween indices 
ranger = np.arange(15)

ranger

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
ser3.reindex(ranger, method='ffill')

0        USA
1        USA
2        USA
3        USA
4        USA
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14    Canada
dtype: object

In [29]:
#Reindexing rows, columns or both

#Lets make a datafram ewith some random values
dframe = DataFrame(randn(25).reshape((5,5)),index=['A','B','D','E','F'],columns=['col1','col2','col3','col4','col5'])
dframe

col1      col2      col3      col4      col5
A -0.054417 -0.108459  0.233755 -1.586668 -1.191361
B  0.582568  0.414192  0.319139 -0.522417  0.374572
D -0.791329  3.426135  0.993737 -0.511212 -0.145770
E  0.611208  2.861592  0.576967  1.798724  0.264839
F  1.194861 -0.678028  1.543486  1.008073  2.212407

In [30]:
#Notice we forgot 'C' , lets reindex it into dframe
dframe2 = dframe.reindex(['A','B','C','D','E','F'])
dframe2

col1      col2      col3      col4      col5
A -0.054417 -0.108459  0.233755 -1.586668 -1.191361
B  0.582568  0.414192  0.319139 -0.522417  0.374572
C       NaN       NaN       NaN       NaN       NaN
D -0.791329  3.426135  0.993737 -0.511212 -0.145770
E  0.611208  2.861592  0.576967  1.798724  0.264839
F  1.194861 -0.678028  1.543486  1.008073  2.212407

In [31]:
#we can also explicitly reindex columns
new_columns = ['col1','col2','col3','col4','col5','col6']

dframe2.reindex(columns=new_columns)


col1      col2      col3      col4      col5  col6
A -0.054417 -0.108459  0.233755 -1.586668 -1.191361   NaN
B  0.582568  0.414192  0.319139 -0.522417  0.374572   NaN
C       NaN       NaN       NaN       NaN       NaN   NaN
D -0.791329  3.426135  0.993737 -0.511212 -0.145770   NaN
E  0.611208  2.861592  0.576967  1.798724  0.264839   NaN
F  1.194861 -0.678028  1.543486  1.008073  2.212407   NaN

In [32]:
#Reindex quickly using the label-indexing with ix (we'll see this more in the future)

#Show original
dframe

dframe3 = dframe.loc[['A','B','C','D','E','F'],new_columns]

In [33]:
dframe3

col1      col2      col3      col4      col5  col6
A -0.054417 -0.108459  0.233755 -1.586668 -1.191361   NaN
B  0.582568  0.414192  0.319139 -0.522417  0.374572   NaN
C       NaN       NaN       NaN       NaN       NaN   NaN
D -0.791329  3.426135  0.993737 -0.511212 -0.145770   NaN
E  0.611208  2.861592  0.576967  1.798724  0.264839   NaN
F  1.194861 -0.678028  1.543486  1.008073  2.212407   NaN

## Drop Entry

In [34]:
ser1

A    1
B    2
C    3
D    4
dtype: int64

In [35]:
# drop an index
ser1.drop('B')

A    1
C    3
D    4
dtype: int64

In [36]:
# we can drop values from either axis in the DataFrame
dframe1 = DataFrame(np.arange(25).reshape((5,5)), 
                    index=['SF','LA','NY','AUS','PHI'],
                    columns=['pop', 'size', 'year', 'unemployment', 'taxrate'])
dframe1

pop  size  year  unemployment  taxrate
SF     0     1     2             3        4
LA     5     6     7             8        9
NY    10    11    12            13       14
AUS   15    16    17            18       19
PHI   20    21    22            23       24

In [37]:
dframe1.drop('PHI')

pop  size  year  unemployment  taxrate
SF     0     1     2             3        4
LA     5     6     7             8        9
NY    10    11    12            13       14
AUS   15    16    17            18       19

In [38]:
# we can also drop a column
dframe1.drop('year', axis=1)

pop  size  unemployment  taxrate
SF     0     1             3        4
LA     5     6             8        9
NY    10    11            13       14
AUS   15    16            18       19
PHI   20    21            23       24

## Selecting entries

In [39]:
ser1 =  Series(np.arange(3), index=['A','B','C'])
print(ser1.values)
# multiply all values of series with a constant
ser1 = ser1 * 5
print(ser1.values)

[0 1 2]
[ 0  5 10]


In [40]:
dframe = DataFrame(np.arange(25).reshape((5,5)),index=['NYC','LA','SF','DC','Chi'],columns=['A','B','C','D','E'])
dframe

A   B   C   D   E
NYC   0   1   2   3   4
LA    5   6   7   8   9
SF   10  11  12  13  14
DC   15  16  17  18  19
Chi  20  21  22  23  24

In [41]:
# selecting by column name
print(dframe['B'])

# selecting multiple column name
print(dframe[['B','C']])

# using boolean filter
print([dframe['C'] > 10])
print(dframe[dframe['C'] > 10])


NYC     1
LA      6
SF     11
DC     16
Chi    21
Name: B, dtype: int64
      B   C
NYC   1   2
LA    6   7
SF   11  12
DC   16  17
Chi  21  22
[NYC    False
LA     False
SF      True
DC      True
Chi     True
Name: C, dtype: bool]
      A   B   C   D   E
SF   10  11  12  13  14
DC   15  16  17  18  19
Chi  20  21  22  23  24


## Summary Statistics

In [42]:
# dataframe
arr = np.array([[1,2,np.nan],[np.nan,3,4]])
dframe1 = pd.DataFrame(arr, index = ['A','B'], columns=['One','Two','Three'])
dframe1

One  Two  Three
A  1.0  2.0    NaN
B  NaN  3.0    4.0

In [43]:
# sum method
print(dframe1.sum())
print(dframe1.sum(axis=1))

One      1.0
Two      5.0
Three    4.0
dtype: float64
A    3.0
B    7.0
dtype: float64


In [44]:
# min and max
print(dframe1.min())
print(dframe1.idxmin())
print(dframe1.max())
print(dframe1.idxmax())

One      1.0
Two      2.0
Three    4.0
dtype: float64
One      A
Two      A
Three    B
dtype: object
One      1.0
Two      3.0
Three    4.0
dtype: float64
One      A
Two      B
Three    B
dtype: object


In [45]:
dframe1.describe()

One       Two  Three
count  1.0  2.000000    1.0
mean   1.0  2.500000    4.0
std    NaN  0.707107    NaN
min    1.0  2.000000    4.0
25%    1.0  2.250000    4.0
50%    1.0  2.500000    4.0
75%    1.0  2.750000    4.0
max    1.0  3.000000    4.0

In [46]:
# Correlation and covariance on stock prices

import pandas_datareader.data as wb
import datetime as dt

start_date = dt.datetime(2017,1,1)
end_date = dt.datetime(2018,1,1)

#stockPrices = data.get_data_yahoo('AAPL', start_date, end_date)['Adj Close']
stock_prices = wb.DataReader(['FB','CVX'], 'robinhood')['close_price']
type(stock_prices)
stock_price_df = pd.DataFrame(stock_prices)